### PR TITLE
Single page

### PR DESCRIPTION
**Pull request by abenaTenkorang**
**In this pull request**

- Create a Single Page App
- Fix Linters Errors
- Follow GitHub Flow

### CODE REVIEW

**Review by Whoistolu — COMMENTED** [review]
Hi Team,
@abenaTenkorang and @mesfin345 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pair-programming project that should have equal commits or commits that are not greater or less than 5. This is to ensure teamwork and show that both partners understand the milestone.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by abenaTenkorang** [comment]
My partner has been having problems with his internet and electricity and hence ha not be available the entire time.

**Comment by Whoistolu** [comment]
> My partner has been having problems with his internet and electricity and hence ha not be available the entire time.

Hello @abenaTenkorang , kindly report this issue to Student Success.

**Review by franclobo — APPROVED** [review]
Hi @abenaTenkorang, 

# STATUS: APPROVED 😃 👏🏽 👏🏽 👏🏽 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️
- Descriptive PR ✔️
- Professional README file ✔️

## Optional suggestions

- [x] **[OPTIONAL]** Kindly report to Student Success when you have any problem with your partner they will help you to have a good experience in pair programming, ⚠️ don't wait until the end ⚠️.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
